package com.linku.domain.bean

import androidx.compose.ui.graphics.Color

data class ComposeTheme(
    val isDark: Boolean,
    val name: String,
    val primary: Color,
    val onPrimary: Color,
    val primaryDisable: Color,
    val onPrimaryDisable: Color,
    val surface: Color,
    val onSurface: Color,
    val secondarySurface: Color,
    val onSecondarySurface: Color,
    val background: Color,
    val onBackground: Color,
    val pressed: Color,
    val onPressed: Color,
    val chatBackground: Color,
    val bubbleEnd: Color,
    val onBubbleEnd: Color,
    val bubbleStart: Color,
    val onBubbleStart: Color,
    val divider: Color,
    val error: Color,
    val onError: Color,
    val id: Int = -1
)

val seaSalt = ComposeTheme(
    isDark = false,
    name = "sea salt",
    primary = Color(0xff837fc9),
    onPrimary = Color(0xffeef7fb),
    surface = Color(0xFFeeeeee),
    onSurface = Color(0xFF191C1B),
    secondarySurface = Color(0xff837fc9),
    onSecondarySurface = Color(0xffeef7fb),
    chatBackground = Color(0xff7eb2a8),
    bubbleStart = Color(0xffefefef),
    onBubbleStart = Color(0xff000000),
    background = Color(0xfffefefe),
    onBackground = Color(0xff2a2a2a),
    pressed = Color(0xfff8f8f8),
    onPressed = Color(0xff323232),
    primaryDisable = Color(0xffc7c6cb),
    onPrimaryDisable = Color(0xfff6f5f9),
    bubbleEnd = Color(0xff5a91de),
    onBubbleEnd = Color(0xffdcf7fa),
    divider = Color(0xFFf0f0f0),
    error = Color(0xFFBA1A1A),
    onError = Color.White
)
val midNight = ComposeTheme(
    isDark = true,
    name = "mid night",
    primary = Color(0xff42b6fe),
    surface = Color(0xff232325),
    onSurface = Color(0xFFffffff),
    secondarySurface = Color(0xff232325),
    onSecondarySurface = Color(0xFFffffff),
    chatBackground = Color(0xff141622),
    bubbleStart = Color(0xff202123),
    onBubbleStart = Color(0xffffffff),
    background = Color(0xff181818),
    onBackground = Color(0xffffffff),
    pressed = Color(0xff222222),
    onPressed = Color(0xff323232),
    primaryDisable = Color(0xff8e8e8e),
    onPrimaryDisable = Color(0xff8e8e8e),
    onPrimary = Color(0xffffffff),
    bubbleEnd = Color(0xff387ab4),
    onBubbleEnd = Color(0xffeef5f9),
    divider = Color(0xFF0A0A0A),
    error = Color(0xfff2b8b5),
    onError = Color(0xff601410)
)

val frigidity = ComposeTheme(
    isDark = false,
    name = "frigidity",
    primary = Color(0xff81a0f3),
    surface = Color(0xff6877ad),
    onSurface = Color(0xFFffffff),
    secondarySurface = Color(0xff7388c9),
    onSecondarySurface = Color(0xFFffffff),
    chatBackground = Color(0xffcdd6df),
    bubbleStart = Color(0xfffefefe),
    onBubbleStart = Color(0xff0f0f0f),
    background = Color(0xffffffff),
    onBackground = Color(0xff000000),
    pressed = Color(0xff222222),
    onPressed = Color(0xff323232),
    primaryDisable = Color(0xfff6f6f6),
    onPrimaryDisable = Color(0xff81a0f3),
    onPrimary = Color(0xfffcfcf5),
    bubbleEnd = Color(0xfffdf2d4),
    onBubbleEnd = Color(0xffba8800),
    divider = Color(0xFFefefef),
    error = Color(0xFFBA1A1A),
    onError = Color.White
)